name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name flask-app-container flask-app
        
      - name: Wait for Docker container to be ready
        run: |
          echo "Waiting for container to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:5000; then
              echo "Container is ready!"
              exit 0
            fi
            echo "Retrying in 2 seconds..."
            sleep 2
          done
          echo "Container did not become ready in time."
          exit 1

      - name: Test the app
        run: curl -f http://localhost:5000

      - name: Erase Docker
        run: docker rm -f flask-app-container